### ISSUE TITLE
Remove missing license warning after submission approval/denial

### ISSUE THREAD

**Issue by JeremyEspresso** [TheCodingDen/projects-bot#137]
After the approval/denial of a project. The warning:
![image](https://user-images.githubusercontent.com/58816840/109304377-79193c80-783c-11eb-8df9-2d4e8c0ac303.png)
should be removed from the submissions channel.

**Comment by linuswillner** [comment]
This should really just apply to any warning for a given project, not just missing license warnings.

**Comment by JeremyEspresso** [comment]
Agreed, this was the first warning I came across thus far.
