### ISSUE TITLE
fix: remove the CC from the rejection message if there is nobody to CC

### ISSUE THREAD

**Issue by BobobUnicorn** [TheCodingDen/projects-bot#152]
It's a little odd to see the bot tell you to send a message in the same thread.

**Comment by nullishamy** [comment]
it was specifically requested and agreed on that the vets would like the human to remain as the original sender of rejection messages.

**Comment by BobobUnicorn** [comment]
We may want to send the message in the submission review thread then?

**Comment by nullishamy** [comment]
once the user copies the message from the bot, the bot message is removed, btw

**Comment by BobobUnicorn** [comment]
Little strange, but ok. Might want to remove CCs if there's nobody to CC.

**Comment by nullishamy** [comment]
see #107.
