### ISSUE TITLE
feat: suspend/unsuspend command

### ISSUE THREAD

**Issue by BobobUnicorn** [TheCodingDen/projects-bot#16]
Currently, if a person suspends a project, then either stops being staff or leaves, there is no way to unsuspend the project from voting. An alternative would be to have a staff command that can just suspend or unsuspend a project independent of who originally suspended it. We should also indicate that the project is suspended in the embed somewhere.

**Comment by nullishamy** [comment]
Pausing / unpausing can be done by anyone now, independent of who did it originally.
