### ISSUE TITLE
Utilize threads for discussion

### ISSUE THREAD

**Issue by Quozlet** [TheCodingDen/projects-bot#274]
Trying to link discussions to currently 'active' projects is confusing. Since threads still persist after removal of the message, it should be possible to have some minor discussion before being archived

**Comment by linuswillner** [comment]
Do you suggest to automatically create a thread in the review channel for each submission?

**Comment by Quozlet** [comment]
When I made this I meant it like an option, but given the bot also responding to project submissions then I think that would be simplest yeah
