### ISSUE TITLE
Alter approval/rejection system to weight staff votes equally

### ISSUE THREAD

**Issue by BobobUnicorn** [TheCodingDen/projects-bot#276]
Copied from Trello:

I think instead of the current system (3 vets or 1 staff to decide either way) we should consider a system where any 2 votes approve or reject the submission, with a veto function for staff to reject inappropriate projects immediately. This way, it will be easier for vets to keep the project submission backlog down, and staff members don't have as much responsibility when voting on projects submitted.

**Comment by nullishamy** [comment]
Should this "veto system" use interactions or text based commands for its functionality? And what sort of reasons would we reject for, deemed "inappropriate"?

**Comment by nullishamy** [comment]
Instant rejection of projects with preset reasons was implemented in #301. We could easily change the default config to finish this off, if we decide this is what we want to do.

**Comment by BobobUnicorn** [comment]
It's still relevant, yes.
