### ISSUE TITLE
Refactor the project and add more abstractions

### ISSUE THREAD

**Issue by nullishamy** [TheCodingDen/projects-bot#290]
In order for development of the bot to continue, we need to refactor the project to make the code easier to understand, work with and iterate on. 

We should also add more abstractions for various operations such as using the DB, actioning projects, and data validation. We should consider using a custom d.js client with extra managers attached for managing the above operations. 

This would make the code much easier to write & maintain, as well as adding stability to the project. 

This would also incorporate #280.

**Comment by Quozlet** [comment]
What's the TL;DR for #293?
